apiVersion: apps/v1
kind: Deployment
metadata:
  name: lsc-wsd-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      volumes:
        - name: web-content
          persistentVolumeClaim:
            claimName: lsc-wsd-pvc
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag  }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: web-content
              mountPath: /usr/share/nginx/html